name: Gettext Updates
on:
  push:
    branches: dev
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/gettext-template@master
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
      with:
        regenerate_po: 'true'
